name: Ubuntu 20.04 ApPredict test suite

on:
  push:
    branches:
      - master
      
  schedule:
    - cron:  '0 0 * * *'
    
  workflow_dispatch:
  
jobs:

  build-and-test:

    name: Build and test on Ubuntu 20.04
    runs-on: ubuntu-20.04
    env:
      CHASTE_TEST_OUTPUT: ${{ github.workspace }}/chaste-test-dir
      CC: gcc
      CXX: g++
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      
    steps:
    - name: set number of processors
      run: |
        echo "NPROC=$(( $(nproc) < 12 ? $(nproc) : 12 ))" >> $GITHUB_ENV
        
    - name: checkout Chaste repository
      uses: actions/checkout@v3
      with:
        repository: Chaste/Chaste
        path: Chaste
        submodules: recursive
        
    - name: ${CXX} version
      run: |
        ${CXX} --version
        ${CXX} --version > compiler.version
        
    - name: send notifications
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: github-actions
        status: FAILED
        color: danger
